config/routes.rb
Rails.application.routes.draw do

  resources :companions
  resources :providers
  resources :expenses
  resources :incomes do 
    collection do 
      get :modal_new
    end
  end
  resources :rentals do
    collection do 
      post :finalizar
      post :cancelar
      post :informado
      post :enviarCorreo
      post :controlarReserva
      get :modal_luz
    end
  end
  
  resources :phones
  resources :emails
  resources :people
  resources :document_types
  resources :categories
  resources :nationalities
  resources :cottages
  resource :sessions, only: [:create, :new]
  resources :identities

  
  delete 'log_out' => 'sessions#destroy', as: :log_out
  get 'log_in' => 'sessions#new', as: :log_in
  get 'sign_up' => 'identities#new', as: :sign_up
  
  get 'welcome/index'
  get 'welcome/index_wiz'
  get 'welcome/calendarfull'
  
  get 'clientes' => 'people#index_cliente'
  get 'duenoscobro/:id_dueno', to: 'people#duenoscobro', as:'duenoscobro'
  get 'reporteduenos', to: 'people#reporteduenos', as:'reporteduenos'
  get 'clientes_rentas', to: 'people#clientes_rentas', as:'clientes_rentas'
  get 'clientes_rentas_faltantes', to: 'people#clientes_rentas_faltantes', as:'clientes_rentas_faltantes'
  get 'agendacuentas', to: 'people#agendacuentas', as:'agendacuentas'
  
  get 'reporte_ganancias', to: 'people#reporte_ganancias'
  get 'reporte_ganancias_detalle', to: 'people#reporte_ganancias_detalle', as: 'reporte_ganancias_detalle'

  get 'reporteCasa/:id_rep', to: 'cottages#reporte', as: 'rep'
  get 'calendariocasa', to: 'cottages#calendariocasa'
  get 'balance_fecha', to: 'incomes#balance_fecha', as: 'balance_fecha'
  get 'balance_afecha/:cottage_id/:fecha_d/:fecha_h', to: 'incomes#balance_afecha', as: 'balance_afecha'
  get 'balance', to: 'incomes#balance', as: 'balance'

  get 'ingresopdf/:id_rent', to: 'rentals#ingresopdf', as:'ingresopdf'
 
  root 'welcome#index'


  # CK editor
  mount Ckeditor::Engine => '/ckeditor'
end

app/models/person.rb
class Person < ApplicationRecord
  attr_encrypted_options.merge!(:encode => true)
  attr_encrypted :cuenta_banco, :key => 'asdasd3434341231235454578...----1113123'
  attr_encrypted :documento, :key => 'asdasd3434341231235454578...----1113123'
  attr_encrypted :nombres, :key => 'asdasd3434341231235454578...----1113123'
  attr_encrypted :apellidos, :key => 'asdasd3434341231235454578...----1113123'
  attr_encrypted :ciudad, :key => 'asdasd3434341231235454578...----1113123'
  attr_encrypted :domicilio, :key => 'asdasd3434341231235454578...----1113123'
  attr_encrypted :matricula_coche, :key => 'asdasd3434341231235454578...----1113123'
  attr_encrypted :segundo_ape, :key => 'asdasd3434341231235454578...----1113123'
  attr_encrypted :segundo_nom, :key => 'asdasd3434341231235454578...----1113123'


  belongs_to :nationality, required: false
  belongs_to :document_type, required: false
  has_many :emails, dependent: :destroy
  has_many :phones, dependent: :destroy
  has_many :rentals, dependent: :destroy
  has_many :expenses, dependent: :destroy
  
  accepts_nested_attributes_for :phones, reject_if: proc { |attributes| attributes['numero'].blank? }, allow_destroy: true
  accepts_nested_attributes_for :emails, reject_if: proc { |attributes| attributes['email'].blank? }, allow_destroy: true
  accepts_nested_attributes_for :rentals,  allow_destroy: true
  
  
  def nom_ape
      "#{nombres}, #{apellidos}"
  end
  
  
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]
  before_action :authenticate!
  # GET /people
  # GET /people.json
  def index
    @people = Person.where(:tipo => "D")
  end
  
  def index_cliente
    @people = Person.where(:tipo => "C")
  end

  
  def clientes_rentas
    @rentals = Rental.all
    @companions = Companion.all
    @continuar = "S"
  end
  
  def clientes_rentas_faltantes
    @rentals = Rental.all
    @companions = Companion.all
  end

  def duenoscobro
    #User.joins(:posts).where("posts.created_at < ?", Time.now)
    @rentals = Rental.joins("INNER JOIN cottages ON cottages.id = rentals.cottage_id AND cottages.person_id ="+params[:id_dueno])
    @dueno = Person.find(params[:id_dueno])
  end
 
 
  def reporte_ganancias
     @duenos = Person.where(:tipo => "D")  
  end
  
  def reporte_ganancias_detalle
   
    @id = params[:id_dueno][:person_id]
    
    @dueno = Person.find(@id)
    @fecha_desde = params[:fecha_desde].to_datetime.strftime("%Y-%m-%d")
    @fecha_hasta = params[:fecha_hasta].to_datetime.strftime("%Y-%m-%d")
    
    @rentals = Rental.find_by_sql("SELECT rentals.* FROM rentals, cottages WHERE cottages.id = rentals.cottage_id AND cottages.person_id =" + @id + " AND cottages.tipo = 'D' AND rentals.fechadesde >= '" + @fecha_desde +"' and rentals.fechadesde <= '" + @fecha_hasta + "' AND rentals.estado <> 'cancelada' order by rentals.fechadesde  ")

    @gastos = Expense.find_by_sql("SELECT e.* FROM expenses e, cottages c WHERE e.fecha >= '" +  @fecha_desde + "' AND e.fecha <= '" + @fecha_hasta + "' AND e.cottage_id  = c.id AND c.person_id = " + @id + " AND c.tipo= 'D' order by e.fecha" )
  end
 
  def agendacuentas
    @people = Person.where(:tipo => "D")
  end
  
  # GET /people/1
  # GET /people/1.json
  def show
    @person.phones.build 
    @person.emails.build
  end

  # GET /people/new
  def new
    @person = Person.new
    @person.phones.build 
    @person.emails.build
    @person.tipo = params[:tipo]
  end

  # GET /people/1/edit
  def edit
    @person.phones.build 
    @person.emails.build
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)
      
    respond_to do |format|
      if @person.save
        @person.rentals.each do |r|
          if r.incomes.present?
            if r.may_confirmar?
                r.confirmar
                r.save
            end
          end
        end
        if @person.tipo == "C"
          if params[:commit] == "Finalizar"
            format.html { redirect_to root_path , notice: 'Alquiler guardado correctamente.' }
          else  
            format.html { redirect_to clientes_path , notice: 'Cliente guardado correctamente.' }
          end
           
        else
          format.html { redirect_to people_path , notice: 'Dueño guardada correctamente.' }
        end
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
     
    respond_to do |format|
      if @person.update(person_params)
        
        if @person.tipo == "C"
          format.html { redirect_to clientes_path , notice: 'Cliente actualizado correctamente.' }
        else
          format.html { redirect_to people_path , notice: 'Dueño actualizado correctamente.' }
        end
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @tipo  = @person.tipo
    @person.destroy
    respond_to do |format|
      if @tipo == "C"
        format.html { redirect_to clientes_path , notice: 'Cliente borrado correctamente.' }
      else
        format.html { redirect_to people_path , notice: 'Dueño borrado correctamente.' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:documento, :nombres, :apellidos, :ciudad, :domicilio, :fecha_nac, :matricula_coche, :tipo,:segundo_ape, :segundo_nom, :pais_residencia, :pais_origen_doc, 
        :sexo,:nationality_id, :document_type_id, :cuenta_banco, phones_attributes: [ :id, :descripcion, :numero  ], emails_attributes: [ :id, :descripcion, :email, :_destroy ], rentals_attributes: [:id,:fechadesde, :fechahasta, :valordia, :medidoringreso, :medidorfin, :valorkw, :cant_acomp, :informado, :descripcion, :cottage_id,:fecha_entrega,:hora_entrega,:hora_entrada,:costo_total,:estado,:ganancia_dueno,:transporte,:id_dueno, incomes_attributes:[ :fecha, :tipo, :importe, :rental_id],
          companions_attributes: [ :id, :nombre, :seg_nombre, :apellido, :seg_apellido, :documento, :pais_origen_doc, :document_type_id, :sexo, :nationality_id, :fecha_nac, :pais_residencia, :rental_id ]
        ])
    end
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/clientes_rentas_faltantes.html.erb
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">
  
    <span class="ribbon-button-alignment">
      <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Advertencia! se perderán los cambios no guardados. " data-html="true">
        <i class="fa fa-refresh"></i>
      </span>
    </span>
  
    <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li><%= link_to 'Inicio', root_path %></li>
      <li><%= link_to 'Clientes datos incompletos', clientes_path %></li>   
    </ol>

    <!-- end breadcrumb -->
  </div>
<!-- END RIBBON -->
<% end %>

<!-- MAIN CONTENT -->
<div id="content">

  <!-- widget grid -->
  <section id="widget-grid" class="">
    <!-- row -->
    <div class="row">

      <!-- NEW WIDGET START -->
      <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                
        <!-- Widget ID (each widget will need unique ID)-->
        <div class="jarviswidget jarviswidget-color-green" id="wid-id-3" data-widget-editbutton="false">
     
          <header>
            <span class="widget-icon"> <i class="fa fa-table"></i> </span>
            <h2>Personas</h2>  
          </header>
  
          <!-- widget div-->
          <div>
  
            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
              <!-- This area used as dropdown edit box -->  
            </div>
            <!-- end widget edit box -->
  
            <!-- widget content -->
            <div class="widget-body no-padding">
  
              <table id="datatable_tabletools" class="table table-striped table-bordered table-hover" width="100%">
                <thead>
                  <tr>
                    <th data-hide="expand">documento</th>
                    <th data-hide="phone">idpaisdocumento</th>
                    <th data-hide="phone">tipodocumento</th>
                    <th data-hide="phone">apellido1</th>
                    <th data-hide="phone">nombre1</th>
                    <th data-hide="expand">Acciones Persona</th> 
                    <th data-hide="expand">Acciones Alquiler</th> 
                  </tr>
                </thead>
                <tbody>
                  <% @rentals.each do |rental| %>
                    <% if rental.informado != "S" %>
                        <% if rental.encurso? %>
                            <% if !rental.person.documento or !rental.person.pais_origen_doc or !rental.person.document_type  or !rental.person.sexo or !rental.person.nationality or !rental.person.pais_residencia or !rental.fechadesde or !rental.fechahasta or !rental.person.fecha_nac %>
                              <tr>
                                  <td><%= rental.person.documento %></td>        
                                  <td><%= rental.person.pais_origen_doc %></td>
                                  <td><%= rental.person.document_type.codigo if rental.person.document_type %></td>
                                  <td><%= rental.person.apellidos %></td>    
                                  <td><%= rental.person.nombres %></td>
                                  <td>
                                      <%= link_to '', rental.person, class: 'btn btn-xs btn-default fa fa-eye'%>
                                      <%= link_to '', edit_person_path(rental.person) , class: 'btn btn-xs btn-default fa fa-pencil' %>
                                  </td>
                                  <td>
                                      <%= link_to '', rental, class: 'btn btn-xs btn-default fa fa-eye'%>
                                      <%= link_to '', edit_rental_path(rental) , class: 'btn btn-xs btn-default fa fa-pencil' %>
                                  </td>
                              </tr>
                            <% end %>
                        <% end %>
                      <% end %>
                  <% end %>     
                  <% @companions.each do |companion| %>
                      
                      <% if companion.rental.encurso? %>
                        <% if !companion.documento || !companion.nombre || !companion.apellido || !companion.pais_origen_doc || !companion.document_type || !companion.sexo || !companion.fecha_nac || !companion.pais_residencia || !companion.nationality %>
                          <tr>
                            <td><%= companion.documento %></td>        
                            <td><%= companion.pais_origen_doc if companion.pais_origen_doc %></td>
                            <td><%= companion.document_type.codigo if companion.document_type %></td>
                            <td><%= companion.apellido %></td>    
                            <td><%= companion.nombre %></td>
                            <td>
                                <%= link_to '', companion, class: 'btn btn-xs btn-default fa fa-eye'%>
                                <%= link_to '', edit_companion_path(companion) , class: 'btn btn-xs btn-default fa fa-pencil' %>
                            </td>
                            <td>
                                <%= link_to '', companion.rental, class: 'btn btn-xs btn-default fa fa-eye'%>
                                <%= link_to '', edit_rental_path(companion.rental) , class: 'btn btn-xs btn-default fa fa-pencil' %>
                            </td>
                          </tr>
                        <% end %>  
                      <% end %> 
                
                  <% end %>  
                </tbody>
              </table>  
            </div>
            <!-- end widget content -->  
          </div>
          <!-- end widget div -->  
        </div>
        <!-- end widget -->  
      </article>
      <!-- WIDGET END -->
    </div>
    <!-- end row -->   
  </section>
  <!-- end widget grid -->
<!-- END MAIN CONTENT -->

 
</div>
<!-- END MAIN CONTENT -->

<% content_for :scripts do %>
  <script type="text/javascript">

    // DO NOT REMOVE : GLOBAL FUNCTIONS!

    $(document).ready(function() {

      pageSetUp();


      var responsiveHelper_datatable_tabletools = undefined;

      var breakpointDefinition = {
        tablet : 1024,
        phone : 480
      };
     
      
      $('#datatable_tabletools').DataTable( {
          dom: "<'dt-toolbar'<'col-xs-12 col-sm-6'f> <'col-sm-6 col-xs-6 hidden-xs'BT>r>"+
              "t"+ "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
          buttons: [
              {
                  extend: 'csvHtml5',
                  text: 'CSV',
                  title: 'Datos Faltantes de Personas',
                  fieldSeparator: ";",
                  exportOptions: {
                      columns: [0,1,2,3,4]
                  }
              },
              {
                  extend: 'pdfHtml5',
                  text: 'PDF',
                  title: 'Datos Faltantes de Personas',
                  exportOptions: {
                      columns: [0,1,2,3,4]
                  }
              },
              {
                  extend: 'excelHtml5',
                  title:'Datos Faltantes de Personas',
                  text: 'EXCEL',
                  exportOptions: {
                      columns: [0,1,2,3,4]
                  }
              }                   
              
          ],
          language: {
              search: '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>',
              processing: "Procesando...",
              lengthMenu:    "Afficher _MENU_ &eacute;l&eacute;ments",
              info:           "Mostrando _END_ de _MAX_ registros",
              infoEmpty:      "No hay datos para mostrar",
              infoFiltered:   "(filtrado de _MAX_ registros totales)",
              infoPostFix:    "",
              loadingRecords: "Cargando registros...",
              zeroRecords:    "No hay datos para mostrar",
              emptyTable:     "No hay datos para mostrar",
              paginate: {
                  first:      "Primer",
                  previous:   "Anterior",
                  next:       "Siguiente",
                  last:       "Ultimo"
              },
             
          },
          "pageLength": 10,
          "autoWidth" : true,
          "preDrawCallback" : function() {
            // Initialize the responsive datatables helper once.
            if (!responsiveHelper_datatable_tabletools) {
              responsiveHelper_datatable_tabletools = new ResponsiveDatatablesHelper($('#datatable_tabletools'), breakpointDefinition);
            }
          },
          "rowCallback" : function(nRow) {
            responsiveHelper_datatable_tabletools.createExpandIcon(nRow);
          },
          "drawCallback" : function(oSettings) {
            responsiveHelper_datatable_tabletools.respond();
          }
          
          
      });
      
       //Cambio clases a los botones de CSV,PDF,XLS
      $(".dt-buttons").addClass("DTTT_container");
      $(".dt-button").addClass("DTTT_button");
      $(".dt-button").removeClass("dt-button buttons-csv buttons-html5");
      $(".dt-buttons").removeClass("dt-buttons");

    })

  </script>
<% end %>

app/views/people/create.js.erb
$("<%= escape_javascript(render @person) %>").appendTo("#peoples");

app/views/people/index.html.erb
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">
  
    <span class="ribbon-button-alignment">
      <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Advertencia! se perderán los cambios no guardados. " data-html="true">
        <i class="fa fa-refresh"></i>
      </span>
    </span>
  
    <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li><%= link_to 'Inicio', root_path %></li>
      <li><%= link_to 'Dueños', people_path %></li>   
    </ol>

    <!-- end breadcrumb -->
  </div>
<!-- END RIBBON -->
<% end %>

<!-- MAIN CONTENT -->
<div id="content">

  <!-- widget grid -->
  <section id="widget-grid" class="">
    <!-- row -->
    <div class="row">

      <!-- NEW WIDGET START -->
      <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                
        <!-- Widget ID (each widget will need unique ID)-->
        <div class="jarviswidget jarviswidget-color-green" id="wid-id-3" data-widget-editbutton="false"  data-widget-deletebutton="false" data-widget-colorbutton="false">
     
          <header>
            <span class="widget-icon"> <i class="fa fa-table"></i> </span>
            <h2>Dueños</h2>  
          </header>
  
          <!-- widget div-->
          <div>
  
            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
              <!-- This area used as dropdown edit box -->  
            </div>
            <!-- end widget edit box -->
  
            <!-- widget content -->
            <div class="widget-body no-padding">
  
              <table id="datatable_tabletools" class="table table-striped table-bordered table-hover" width="100%">
                <thead>
                  <tr>
                    <th data-class="expand">Nombre</th>
                    <th data-hide="phone">Tipo de Documento</th>
                    <th data-hide="phone">Nacionalidad</th>
                    <th data-hide="phone">Nº Documento</th>
                    <th data-hide="expand">Acciones</th>                    
                  </tr>
                </thead>
                <tbody>
                  <% @people.each do |person| %>
                    
                    <tr>
                      <td><%= person.nombres  %>, <%= person.apellidos%></td>        
                      <td><%= person.document_type.nombre if  person.document_type %></td>
                      <td><%= person.nationality.nombre if person.nationality %></td>
                      <td><%= person.documento %></td>                      
                       <td><%= link_to '', person, class: 'btn btn-xs btn-default fa fa-eye'%>
                          <%= link_to '', edit_person_path(person) , class: 'btn btn-xs btn-default fa fa-pencil' %>
                          <%= link_to '', person, method: :delete, data: { confirm: 'Esta seguro que desea eliminar?' }, class: 'btn btn-xs btn-default fa fa-times' %>
                         
                      </td>
                    </tr>
                    
                  <% end %>                   
                </tbody>
              </table>  
            </div>
            <!-- end widget content -->  
          </div>
          <!-- end widget div -->  
        </div>
        <!-- end widget -->  
      </article>
      <!-- WIDGET END -->
    </div>
    <!-- end row -->   
  </section>
  <!-- end widget grid -->

 <br>

 <%= link_to 'Nuevo Dueño', new_person_path(:tipo=> 'D'), class: 'btn btn-success' %>
</div>
<!-- END MAIN CONTENT -->

<% content_for :scripts do %>
  <script type="text/javascript">

    // DO NOT REMOVE : GLOBAL FUNCTIONS!

    $(document).ready(function() {

      pageSetUp();
     
      var responsiveHelper_datatable_tabletools = undefined;

      var breakpointDefinition = {
        tablet : 1024,
        phone : 480
      };
      
     
      $('#datatable_tabletools').DataTable( {
          dom: "<'dt-toolbar'<'col-xs-12 col-sm-6'f> <'col-sm-6 col-xs-6 hidden-xs'BT>r>"+
              "t"+ "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
          buttons: [
              {
                  extend: 'csvHtml5',
                  text: 'CSV',
                  title: 'Dueños',
                  fieldSeparator: ";",
                  exportOptions: {
                      columns: [0,1,2,3]
                  }
              },
              {
                  extend: 'pdfHtml5',
                  text: 'PDF',
                  title: 'Dueños',
                  exportOptions: {
                      columns: [0,1,2,3]
                  }
              },
              {
                  extend: 'excelHtml5',
                  title:'Dueños',
                  text: 'EXCEL',
                  exportOptions: {
                      columns: [0,1,2,3]
                  }
              }                   
              
          ],
          language: {
              search: '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>',
              processing: "Procesando...",
              lengthMenu:    "Afficher _MENU_ &eacute;l&eacute;ments",
              info:           "Mostrando _END_ de _MAX_ registros",
              infoEmpty:      "No hay datos para mostrar",
              infoFiltered:   "(filtrado de _MAX_ registros totales)",
              infoPostFix:    "",
              loadingRecords: "Cargando registros...",
              zeroRecords:    "No hay datos para mostrar",
              emptyTable:     "No hay datos para mostrar",
              paginate: {
                  first:      "Primer",
                  previous:   "Anterior",
                  next:       "Siguiente",
                  last:       "Ultimo"
              },
             
          },
          "pageLength": 10,
          "autoWidth" : true,
          "preDrawCallback" : function() {
            // Initialize the responsive datatables helper once.
            if (!responsiveHelper_datatable_tabletools) {
              responsiveHelper_datatable_tabletools = new ResponsiveDatatablesHelper($('#datatable_tabletools'), breakpointDefinition);
            }
          },
          "rowCallback" : function(nRow) {
            responsiveHelper_datatable_tabletools.createExpandIcon(nRow);
          },
          "drawCallback" : function(oSettings) {
            responsiveHelper_datatable_tabletools.respond();
          }
          
          
      });
      
       //Cambio clases a los botones de CSV,PDF,XLS
      $(".dt-buttons").addClass("DTTT_container");
      $(".dt-button").addClass("DTTT_button");
      $(".dt-button").removeClass("dt-button buttons-csv buttons-html5");
      $(".dt-buttons").removeClass("dt-buttons");

    })

  </script>
<% end %>

app/views/people/reporte_ganancias.html.erb
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">
  
    <span class="ribbon-button-alignment">
      <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Advertencia! se perderán los cambios no guardados. " data-html="true">
        <i class="fa fa-refresh"></i>
      </span>
    </span>
  
     <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li><%= link_to 'Inicio', root_path %></li>
      <li><%= link_to 'Ganancias Dueño', reporte_ganancias_path %></li> 
    </ol>
    <!-- end breadcrumb -->
  </div>
<!-- END RIBBON -->
<% end %>


<!-- MAIN CONTENT -->
<div id="content">

  <!-- widget grid -->
  <section id="widget-grid" class="">
    <!-- row -->
    <div class="row">

      <!-- NEW COL START -->
        <article class="col-sm-12 col-md-12 col-lg-6">
         
          <!-- Widget ID (each widget will need unique ID)-->
          <div class="jarviswidget jarviswidget-color-green" id="wid-id-5" data-widget-colorbutton="false"	data-widget-editbutton="false" data-widget-deletebutton="false" data-widget-sortable="false">
            <header>
              <h2>Reporte Ganancias Dueño </h2>
            </header>

            <!-- widget div-->

            <div>
              <!-- widget edit box -->
              <div class="jarviswidget-editbox">
                <!-- This area used as dropdown edit box -->
                <input class="form-control" type="text">
              </div>
              <!-- end widget edit box -->

              <!-- widget content -->
              <div class="widget-body">

                
                <%= form_tag(reporte_ganancias_detalle_path, method: "get") do %>  
                  <fieldset>
                    
                    <div class="form-group">
                        <label>Dueño</label>
                        <%= collection_select(:id_dueno, :person_id,  @duenos, :id, :nom_ape, { :include_blank => "Seleccionar dueño..."}, {:class=>'form-control', :required => true}) %>
                    </div>    
			        
			        
                    <div class="form-group">
                      <label>Fecha Desde</label>
                        <input type="date" id="fecha_desde" name="fecha_desde" required="true" class="form-control">
                    </div>
                    
                    <div class="form-group">
                      <label>Fecha Hasta</label>
                        <input type="date" id="fecha_hasta" name="fecha_hasta" required="true" class="form-control">
                    </div>
                  </fieldset>
                  
                    
                  <div class="form-actions">
                    <div class="row">
                      <div class="col-md-12">
                        <button class= 'btn btn-success' type="submit">Confirmar</button>
                      </div>
                    </div>
                  </div>
                <% end %>
                
                

              </div>
              <!-- end widget content -->

            </div>
            <!-- end widget div -->

          </div>
          <!-- end widget -->
        </article>
      <!-- WIDGET END -->
    </div>
    <!-- end row -->   
  </section>
  <!-- end widget grid -->
  
 </div>