config/routes.rb
Rails.application.routes.draw do

  resources :companions
  resources :providers
  resources :expenses
  resources :incomes do 
    collection do 
      get :modal_new
    end
  end
  resources :rentals do
    collection do 
      post :finalizar
      post :cancelar
      post :informado
      post :enviarCorreo
      post :controlarReserva
      get :modal_luz
    end
  end
  
  resources :phones
  resources :emails
  resources :people
  resources :document_types
  resources :categories
  resources :nationalities
  resources :cottages
  resource :sessions, only: [:create, :new]
  resources :identities

  
  delete 'log_out' => 'sessions#destroy', as: :log_out
  get 'log_in' => 'sessions#new', as: :log_in
  get 'sign_up' => 'identities#new', as: :sign_up
  
  get 'welcome/index'
  get 'welcome/index_wiz'
  get 'welcome/calendarfull'
  
  get 'clientes' => 'people#index_cliente'
  get 'duenoscobro/:id_dueno', to: 'people#duenoscobro', as:'duenoscobro'
  get 'reporteduenos', to: 'people#reporteduenos', as:'reporteduenos'
  get 'clientes_rentas', to: 'people#clientes_rentas', as:'clientes_rentas'
  get 'clientes_rentas_faltantes', to: 'people#clientes_rentas_faltantes', as:'clientes_rentas_faltantes'
  get 'agendacuentas', to: 'people#agendacuentas', as:'agendacuentas'
  
  get 'reporte_ganancias', to: 'people#reporte_ganancias'
  get 'reporte_ganancias_detalle', to: 'people#reporte_ganancias_detalle', as: 'reporte_ganancias_detalle'

  get 'reporteCasa/:id_rep', to: 'cottages#reporte', as: 'rep'
  get 'calendariocasa', to: 'cottages#calendariocasa'
  get 'balance_fecha', to: 'incomes#balance_fecha', as: 'balance_fecha'
  get 'balance_afecha/:cottage_id/:fecha_d/:fecha_h', to: 'incomes#balance_afecha', as: 'balance_afecha'
  get 'balance', to: 'incomes#balance', as: 'balance'

  get 'ingresopdf/:id_rent', to: 'rentals#ingresopdf', as:'ingresopdf'
 
  root 'welcome#index'


  # CK editor
  mount Ckeditor::Engine => '/ckeditor'
end

app/models/cottage.rb
class Cottage < ApplicationRecord
    belongs_to :person, required: false
    has_many :rentals, dependent: :destroy
    has_many :expenses, dependent: :destroy
    
end

app/controllers/cottages_controller.rb
class CottagesController < ApplicationController
  before_action :set_cottage, only: [:show, :edit, :update, :destroy ]
  before_action :authenticate!
  # GET /cottages/
  # GET /cottages.json
  def reporte
    @rentals = Rental.where(:cottage_id => params[:id_rep])
  end
  
  def calendariocasa
    @cottages = Cottage.all
    @rentals = Rental.all
  end
  def index
    @cottages = Cottage.all
  end

  # GET /cottages/1
  # GET /cottages/1.json
  def show
  end

  # GET /cottages/new
  def new
    @cottage = Cottage.new
  end

  # GET /cottages/1/edit
  def edit
  end

  # POST /cottages
  # POST /cottages.json
  def create
    @cottage = Cottage.new(cottage_params)
    
    respond_to do |format|
      if @cottage.save
        format.html { redirect_to cottages_path , notice: 'Casa guardada correctamente.' }
      else
        format.html { render :new }
        format.json { render json: @cottage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cottages/1
  # PATCH/PUT /cottages/1.json
  def update
    
    respond_to do |format|
      if @cottage.update(cottage_params)
        format.html { redirect_to cottages_path, notice: 'Casa actualizada correctamente.' }
      else
        format.html { render :edit }
        format.json { render json: @cottage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cottages/1
  # DELETE /cottages/1.json
  def destroy
    @cottage.destroy
    
    respond_to do |format|
      format.html { redirect_to cottages_url, notice: 'Casa eliminada correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cottage
      @cottage = Cottage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cottage_params
      params.require(:cottage).permit(:nombre, :capacidad, :descripcion,:tipo, :person_id, :rep_id, )
    end
end

app/helpers/cottages_helper.rb
module CottagesHelper
end

app/views/cottages/_form.html.erb
<script>
    function verD2() {
        var tipo = $(cottage_tipo).val(); 
        if (tipo=='P'){
          $("#section_person").css({'display':'none'});
          $("#cottage_person_id").val("0"); 
          $('#cottage_person_id > option[value=""]').attr('selected', 'selected');
        }else {
          $("#section_person").css('display','block');
        }
    }
    window.onload= verD2;
</script>

    <!-- Widget ID (each widget will need unique ID)-->
    <div class="jarviswidget jarviswidget-color-green" id="wid-id-3" data-widget-editbutton="false"  data-widget-deletebutton="false" data-widget-colorbutton="false" >
   
    <header>
      <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
      <h2>Casa</h2>  
    </header>
  
    <!-- widget div-->
    <div>
  
      <!-- widget edit box -->
      <div class="jarviswidget-editbox">
        <!-- This area used as dropdown edit box -->
  
      </div>
      <!-- end widget edit box -->
  
      <!-- widget content -->
      <div class="widget-body no-padding" >
  
        <%= form_for(@cottage, html:{:class => 'smart-form'}) do |f| %>
            <% if @cottage.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@cottage.errors.count, "error") %> prohibited this identity from being saved:</h2>          
                <ul>
                <% @cottage.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
          
  
          <fieldset>          
            
            <section>
              <label>Nombre</label>
              <label class="input"> <i class="icon-append fa fa-home"></i>
                <%= f.text_field :nombre, placeholder: 'Nombre', required: true %>     
              </label>
            </section>
  
            <section>
              <label>Capacidad</label>
              <label class="input"> <i class="icon-append fa fa-group"></i>                
                <%= f.text_field :capacidad,  placeholder: 'Capacidad', required: true %>
              </label>
            </section>
          
            <section>
              <label>Descripción</label>
              <label class="input"> <i class="icon-append fa fa-comment"></i>               
                   <%= f.text_field :descripcion, placeholder: 'Descripción', required: true %>
              </label>
            </section>
           
            <section>
              <label class="input"> Tipo de casa
                <%= f.select :tipo, [['Propia', 'P'], ['Dueño', 'D']],{:include_blank => "Seleccionar tipo..."}, :onchange => 'verD2();',
                placeholder: 'Tipo', required: true, class:"form-control"  %>     
              </label>
            </section>
            
            <section id="section_person" style="display:none" >
              <label class="input" for="">Dueño</label>
              <%= f.collection_select  :person_id, Person.where(:tipo => "D"), :id, :nom_ape, { :include_blank => "Seleccionar dueño..."}, {:class=>'form-control'}  %>
				      
            </section>
        
            
          </fieldset>
  
          <footer>
            <%= f.submit 'Confirmar', class:'btn btn-success'   %>  
            <div>
               <%= link_to 'Volver', cottages_path, class: 'btn btn-default'  %>
            </div>
          </footer>
        <% end %>
  
      </div>
      <!-- end widget content -->
  
    </div>
    <!-- end widget div -->
  
  </div>
  <!-- end widget -->

app/views/cottages/calendariocasa.html.1.erb
<% content_for :ribbon do %>
	<div id="ribbon">
		<span class="ribbon-button-alignment">
			<span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
				<i class="fa fa-refresh"></i>
			</span>
		</span>
		<ol class="breadcrumb">
			<li><%= link_to 'Inicio', root_path %></li>
			<li>Calendario</li>
		</ol>
	</div>
<% end %>

<div id="content">
	<section id="widget-grid" class="">
	  	<div class="row">
	   		<section class="col-sm-12 col-md-12 col-lg-10">
	        	<div class="jarviswidget jarviswidget-color-green" id="wid-id-0" data-widget-editbutton="false"  data-widget-deletebutton="false" data-widget-colorbutton="false">
	  
		        	<header>
		            	<span class="widget-icon"> <i class="fa fa-calendar"></i> </span>
		            	<h2> Calendario reservas </h2>
		            	<div class="widget-toolbar">
		              	<!-- add: non-hidden - to disable auto hide -->
		            	</div>
		          	</header>
	  
	              	<div>
		            	<div class="widget-body no-padding">
							<div id="br">
								<br/>
								<br/>
		            			<div id="calendar">
		                
		          				</div>  
			
			              	</div>
		              	</div>
		            </div>
	      		</div>
	       	</section>
	         
	        <section class="col-sm-12 col-md-12 col-lg-2">
	  			<div class="form-group">
		        	<strong>Estado de Alquiler</strong>
		          	<div class="row">
		            	<label class="btn bg-color-green "></label>  Ingresada
		            </div>
		            <div class="row">
		            	<label class="btn bg-color-blue "></label>  Confirmada
		            </div>
		            <div class="row">
		            	<label class="btn bg-color-orange "></label>  En Curso
		            </div>
		            <div class="row">
		            	<label class="btn bg-color-red "></label>  Cancelada
		            </div>
		            <div class="row">
		            	<label class="btn bg-color-darken "></label>  Finalizada
		            </div>
		        </div>
		     </section>
	    </div>
	</section>
</div>

<%= render 'extras/modalAltaAlquiler' %>
<%= render 'extras/alertaCalendario' %>

<div id = "desc_dialog" class="dialog" style="display:none;">
  <div id = "rental_edit">
  </div>
</div>
 
<% content_for :scripts do %>
	<!--<link href='https://cdn.rawgit.com/bilygates/estilosonline/master/fullcalendar.min' rel='stylesheet' />
	<link href='https://cdn.rawgit.com/bilygates/estilosonline/master/scheduler.min' rel='stylesheet' />
	
	<script src='https://cdn.rawgit.com/bilygates/estilosonline/master/fullcalendar.min.js'></script>
	<script src='https://cdn.rawgit.com/bilygates/estilosonline/master/moment.min.js'></script>
	<script src='https://cdn.rawgit.com/bilygates/estilosonline/master/scheduler.min.js'></script>-->

	
	<link href='./assets/fullcalendar.min.css' rel='stylesheet' />
	<link href='./assets/fullcalendar.print.css' rel='stylesheet' media='print' />
	<link href='./assets/scheduler.min.css' rel='stylesheet' />


    <script src='./assets/plugin/fullcalendar/moment.min.js' dataType: 'jsonp'></script>
    <script src='./assets/plugin/fullcalendar/fullcalendar.min.js' dataType: 'jsonp'></script>
    <script src='./assets/plugin/fullcalendar/scheduler.min.js' dataType: 'jsonp'></script>
	
	
<!--	<link href='https://fullcalendar.io/js/fullcalendar-scheduler-1.4.0/lib/fullcalendar.min.css' rel='stylesheet' />
	<link href='https://fullcalendar.io/js/fullcalendar-scheduler-1.4.0/lib/fullcalendar.print.css' rel='stylesheet' media='print' />
	<link href='https://fullcalendar.io/js/fullcalendar-scheduler-1.4.0/scheduler.min.css' rel='stylesheet' />


    <script src='https://fullcalendar.io/js/fullcalendar-scheduler-1.4.0/lib/moment.min.js'></script>
    <script src='https://fullcalendar.io/js/fullcalendar-scheduler-1.4.0/lib/fullcalendar.min.js'></script>
    <script src='https://fullcalendar.io/js/fullcalendar-scheduler-1.4.0/scheduler.min.js'></script>-->
	
    <script type="text/javascript">

	$(function() { // document ready
		$('#calendar').fullCalendar({
			now: '<%= Time.now %>',
			schedulerLicenseKey: 'GPL-My-Project-Is-Open-Source',
			editable: false,
			aspectRatio: 1.8,
			scrollTime: '00:00',
			header: {
				left: 'promptResource',
				center: 'title',
			},
			customButtons: {
				promptResource: {
					text: '+ Alquiler',
					click: function() {
						$('#myModal').modal('toggle');
					}
				}
			},
			defaultView: 'timelineMonth',
			views: {
				timelineDay: {
					buttonText: ':15 slots',
					slotDuration: '00:15'
				},
				timelineTenDay: {
					type: 'timeline',
					duration: { days: 10 }
				}
			},
			resourceAreaWidth: '25%',
			resourceLabelText: 'Casas',
			resources: [
				<% @cottages.each do |cottage| %>
					{ 	id: '<%= cottage.id %>' ,
						title: '<%= cottage.nombre %>' },
				<% end %>
			],
			events: [
				<% @rentals.each do |rental| %>
				 	<% if rental.cottage %>
						{ id: '<%= rental.id %>', resourceId: '<%= rental.cottage_id %>', start: '<%= rental.fechadesde %>', end: '<%= rental.fecha_entrega %>', title: '<%= rental.person.nombres %> <%= rental.person.apellidos %>', url: '',
						<% if rental.ingresada? %>
							className: ["event", "bg-color-green"],
						<% elsif rental.confirmada?  %> 
								className: ["event", "bg-color-blue"],
						<% elsif rental.encurso?  %> 
								className: ["event", "bg-color-orange"],
						<% elsif rental.cancelada?  %>
								className: ["event", "bg-color-red"],
						<% elsif rental.finalizada?  %>
								className: ["event", "bg-color-darken"],
						<% end %>
						},
					<% end %>
				<% end %>
			],
			eventRender: function(event, element) {
				element.attr('href', 'javascript:void(0);');
		        element.click(function() {
					<% @rentals.each do |rental| %>
						var id = event.id;
						var idr = '<%= rental.id %>';
						if (id==idr){
							
							var casa_nombre = '<%= rental.cottage.nombre if rental.cottage %>';
							var persona = '<%= rental.person.nombres if rental.person %>, <%= rental.person.apellidos if rental.person %>';
							var fechadesde = '<%= rental.fechadesde if rental.fechadesde %>';
							var fechahasta = '<%= rental.fechahasta if rental.fechahasta %>';
						    var horadesde= '<%= rental.hora_entrada.to_formatted_s(:time) if rental.hora_entrada %>';
						    var horahasta= '<%= rental.hora_entrega.to_formatted_s(:time) if rental.hora_entrega %>';
						    var fechaentrega = '<%= rental.fecha_entrega if rental.fecha_entrega %>';
						    var estado ='<%= rental.estado %>';
						    var pago_luz = '<%= rental.pago_luz %>';
						    var total_luz = '<%= rental.total_luz %>';
						    var total_luz_char = total_luz.toString();
						   
							$('#casa_nombre').val(casa_nombre);
							$('#persona').val(persona);
							$('#fechadesde').val(fechadesde);
							$('#horadesde').val(horadesde);
							$('#horahasta').val(horahasta);
							$('#fechahasta').val(fechahasta);
							$('#fechaentrega').val(fechaentrega);
							if (pago_luz == 'S'){
								 $('#luz_ingreso').val('$ '+ total_luz_char);
							}
								
						
							$("#btn_cancelar").attr('onClick', "cancelar("+idr+");");
						
						    <% rental.person.phones.each do |phone| %>
						    	var p = '<%= phone.numero %>';	
						    	$('#tel1').val(p);
						    <% end %>
						    <% rental.person.emails.each do |email| %>
						    	var e = '<%= email.email %>';	
						    	$('#email').val(e);
						    <% end %>
			
						    $("#btn_ingreso").attr('href', "/ingresopdf/"+idr);
						    $("#btn_ingreso").attr('target', "_blank");
							$("#btn_ingreso").attr('onClick', "window.location.reload(true);");
						
						    $("#btn_finalizar").attr('onClick', "finalizar("+idr+");");
						   
						    $("#btn_confirmar").attr('onClick', "pagar("+idr+");");
						    if (pago_luz == 'S'){
						    	$("#btn_luz").css({'display':'none'});
						    }else{
						    	$("#btn_luz").css({'display':'block'});
						    }
						    $("#btn_luz").attr('onClick', "pagarLuz("+idr+");");
						    
						    $('#ModalDatC').modal('toggle');
							
						}
					<% end %>
		        });
    		},
			
    		
		});
	
	});


	function finalizar(idr){
		jQuery.ajax({
	        data: 'id=' + idr + ', commit= Fin',
	        dataType: "json",
	        //dataType: 'script',
	        type: 'post',
	        url: "/rentals/finalizar",
	        success:function(data) {
	        	if (data.errors) {
			      swal("Error", "No se pudo finalizar. Se permite finalizar si el alquiler esta En Curso o Confirmada.", "error");
			    } else {
			      	swal("Ok", "Finalizada correctamente", "success")
		        	window.location.reload(true);
			    }
	      	}
	    });
	   
	}

	function cancelar(idr){
		jQuery.ajax({
	        data: {"id" : idr, "commit" : "Cancel"},
	        dataType: 'json',
	        type: 'post',
	        url: "/rentals/cancelar",
	        success:function(data) {
	        	if (data.errors) {
			      swal("Error", "No se pudo cancelar. Se permite cancelar si el alquiler esta Ingresado, En Curso o Confirmado.", "error");
			    } else {
			      	swal("Ok", "Cancelada correctamente", "success")
		        	window.location.reload(true);
			    }
		    
	      	}
	    });
	    
	}
	function pagar(idr){
		var importe = 0;
	   jQuery.ajax({
	      url: "/incomes/modal_new/?idr="+ idr + "&importe="+ importe,
	      success: function(data) {
	        $('#rental_edit').html(data['form']);
	        $('#desc_dialog').dialog({
		        title: 'Pagar',
		        modal: true,
		        width: 500,
		        close: function(event, ui){
		            $('#desc_dialog').dialog('destroy')
		        }
		        
		    });
	      } 
	    });
	    
	}
	
	function pagarLuz(idr){
		var importe = 0;
	   jQuery.ajax({
	      url: "/rentals/modal_luz/?idr="+ idr + "&importe="+ importe,
	      success: function(data) {
	        $('#rental_edit').html(data['form']);
	        $('#desc_dialog').dialog({
		        title: 'Pagar',
		        modal: true,
		        width: 500,
		        close: function(event, ui){
		            $('#desc_dialog').dialog('destroy')
		        }
		        
		    });
	      } 
	    });
	    
	}
    </script>

<% end %>

<style>
	#calendar {
		max-width: 900px;
		margin: 10px;
	}
	table td[class*="col-"], table th[class*="col-"] {
    	position: static;
    	float: none;
    
	}

</style>

app/views/cottages/edit.html.erb
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">
  
    <span class="ribbon-button-alignment">
      <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Advertencia! se perderán los cambios no guardados. " data-html="true">
        <i class="fa fa-refresh"></i>
      </span>
    </span>
  
    <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li><%= link_to 'Inicio', root_path %></li>
      <li><%= link_to 'Casas', cottages_path %></li>     
      <li>Editar Casa</li>
    </ol>
    <!-- end breadcrumb -->
  </div>
<!-- END RIBBON -->
<% end %>

<!-- MAIN CONTENT -->
<div id="content">
  <!-- widget grid -->
  <section id="widget-grid" class="">
    <!-- row -->
    <div class="row">

      <!-- NEW COL START -->
        <article class="col-sm-12 col-md-12 col-lg-6">
         

          <%= render 'form' %>


        </article>
      <!-- WIDGET END -->
    </div>
    <!-- end row -->   
  </section>
  <!-- end widget grid -->
  
</div>
							

app/views/cottages/index.html.erb
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">
  
    <span class="ribbon-button-alignment">
      <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Advertencia! se perderán los cambios no guardados. " data-html="true">
        <i class="fa fa-refresh"></i>
      </span>
    </span>
  
    <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li><%= link_to 'Inicio', root_path %></li>
      <li><%= link_to 'Casas', cottages_path %></li>   
    </ol>

    <!-- end breadcrumb -->
  </div>
<!-- END RIBBON -->
<% end %>

<!-- MAIN CONTENT -->
<div id="content">

  <!-- widget grid -->
  <section id="widget-grid" class="">
    <!-- row -->
    <div class="row">

      <!-- NEW WIDGET START -->
      <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                
        <!-- Widget ID (each widget will need unique ID)-->
        <div class="jarviswidget jarviswidget-color-green" id="wid-id-3" data-widget-editbutton="false" data-widget-deletebutton="false" data-widget-colorbutton="false">
     
          <header>
            <span class="widget-icon"> <i class="fa fa-table"></i> </span>
            <h2>Casas</h2>  
          </header>
  
          <!-- widget div-->
          <div>
  
            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
              <!-- This area used as dropdown edit box -->  
            </div>
            <!-- end widget edit box -->
  
            <!-- widget content -->
            <div class="widget-body no-padding">
  
              <table id="datatable_tabletools" class="table table-striped table-bordered table-hover" width="100%">
                <thead>
                  <tr>
                    <th data-class="expand">Nombre</th>
                    <th data-hide="phone">Capacidad</th>
                    <th data-hide="phone">Tipo</th>
                    <th data-hide="phone">Descripción</th>
                    <th data-hide="phone">Dueño</th>
                    <th data-hide="expand">Acciones</th>                    
                  </tr>
                </thead>
                <tbody>
                  <% @cottages.each do |cottage| %>
                    
                    <tr>
                      <td><%= cottage.nombre %></td>        
                      <td><%= cottage.capacidad %></td>
                      <td><%= 'Propia' if cottage.tipo == 'P' %>
                          <%= 'Dueño' if cottage.tipo == 'D' %>
                      </td>
                      <td><%= cottage.descripcion  %></td>
                      <td><%= cottage.person.nom_ape if cottage.person  %></td>
                       <td><%= link_to '', cottage, class: 'btn btn-xs btn-default fa fa-eye'%>
                          <%= link_to '', edit_cottage_path(cottage) , class: 'btn btn-xs btn-default fa fa-pencil' %>
                          <%= link_to '', cottage, method: :delete, data: { confirm: 'Esta seguro que desea eliminar? Se eliminaran todos los alquileres asociados a la casa.' }, class: 'btn btn-xs btn-default fa fa-times' %>
                          <%= link_to '', rep_path(:id_rep => cottage.id) , class: 'btn btn-xs btn-default fa fa-calendar' %>
                      </td>
                    </tr>
                    
                  <% end %>                   
                </tbody>
              </table>  
            </div>
            <!-- end widget content -->  
          </div>
          <!-- end widget div -->  
        </div>
        <!-- end widget -->  
      </article>
      <!-- WIDGET END -->
    </div>
    <!-- end row -->   
  </section>
  <!-- end widget grid -->

<!-- END MAIN CONTENT -->



 <br>
 <%= link_to 'Nueva Casa', new_cottage_path, class: 'btn btn-success' %>
</div>
<!-- END MAIN CONTENT -->

<% content_for :scripts do %>
  <script type="text/javascript">

    // DO NOT REMOVE : GLOBAL FUNCTIONS!

    $(document).ready(function() {

      pageSetUp();

      var responsiveHelper_datatable_tabletools = undefined;

      var breakpointDefinition = {
        tablet : 1024,
        phone : 480
      };
      
     
      $('#datatable_tabletools').DataTable( {
          dom: "<'dt-toolbar'<'col-xs-12 col-sm-6'f> <'col-sm-6 col-xs-6 hidden-xs'BT>r>"+
              "t"+ "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
          buttons: [
              {
                  extend: 'csvHtml5',
                  text: 'CSV',
                  title: 'Casas',
                  fieldSeparator: ";",
                  exportOptions: {
                      columns: [0,1,2,3,4]
                  }
              },
              {
                  extend: 'pdfHtml5',
                  text: 'PDF',
                  title: 'Casas',
                  exportOptions: {
                      columns: [0,1,2,3,4]
                  }
              },
              {
                  extend: 'excelHtml5',
                  title:'Casas',
                  text: 'EXCEL',
                  exportOptions: {
                      columns: [0,1,2,3,4]
                  }
              }                   
              
          ],
          language: {
              search: '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>',
              processing: "Procesando...",
              lengthMenu:    "Afficher _MENU_ &eacute;l&eacute;ments",
              info:           "Mostrando _END_ de _MAX_ registros",
              infoEmpty:      "No hay datos para mostrar",
              infoFiltered:   "(filtrado de _MAX_ registros totales)",
              infoPostFix:    "",
              loadingRecords: "Cargando registros...",
              zeroRecords:    "No hay datos para mostrar",
              emptyTable:     "No hay datos para mostrar",
              paginate: {
                  first:      "Primer",
                  previous:   "Anterior",
                  next:       "Siguiente",
                  last:       "Ultimo"
              },
             
          },
          "pageLength": 10,
          "autoWidth" : true,
          "preDrawCallback" : function() {
            // Initialize the responsive datatables helper once.
            if (!responsiveHelper_datatable_tabletools) {
              responsiveHelper_datatable_tabletools = new ResponsiveDatatablesHelper($('#datatable_tabletools'), breakpointDefinition);
            }
          },
          "rowCallback" : function(nRow) {
            responsiveHelper_datatable_tabletools.createExpandIcon(nRow);
          },
          "drawCallback" : function(oSettings) {
            responsiveHelper_datatable_tabletools.respond();
          }
          
          
      });
      
       //Cambio clases a los botones de CSV,PDF,XLS
      $(".dt-buttons").addClass("DTTT_container");
      $(".dt-button").addClass("DTTT_button");
      $(".dt-button").removeClass("dt-button buttons-csv buttons-html5");
      $(".dt-buttons").removeClass("dt-buttons");

    })

  </script>
<% end %>