config/routes.rb
Rails.application.routes.draw do

  resources :companions
  resources :providers
  resources :expenses
  resources :incomes do 
    collection do 
      get :modal_new
    end
  end
  resources :rentals do
    collection do 
      post :finalizar
      post :cancelar
      post :informado
      post :enviarCorreo
      post :controlarReserva
      get :modal_luz
    end
  end
  
  resources :phones
  resources :emails
  resources :people
  resources :document_types
  resources :categories
  resources :nationalities
  resources :cottages
  resource :sessions, only: [:create, :new]
  resources :identities

  
  delete 'log_out' => 'sessions#destroy', as: :log_out
  get 'log_in' => 'sessions#new', as: :log_in
  get 'sign_up' => 'identities#new', as: :sign_up
  
  get 'welcome/index'
  get 'welcome/index_wiz'
  get 'welcome/calendarfull'
  
  get 'clientes' => 'people#index_cliente'
  get 'duenoscobro/:id_dueno', to: 'people#duenoscobro', as:'duenoscobro'
  get 'reporteduenos', to: 'people#reporteduenos', as:'reporteduenos'
  get 'clientes_rentas', to: 'people#clientes_rentas', as:'clientes_rentas'
  get 'clientes_rentas_faltantes', to: 'people#clientes_rentas_faltantes', as:'clientes_rentas_faltantes'
  get 'agendacuentas', to: 'people#agendacuentas', as:'agendacuentas'
  
  get 'reporte_ganancias', to: 'people#reporte_ganancias'
  get 'reporte_ganancias_detalle', to: 'people#reporte_ganancias_detalle', as: 'reporte_ganancias_detalle'

  get 'reporteCasa/:id_rep', to: 'cottages#reporte', as: 'rep'
  get 'calendariocasa', to: 'cottages#calendariocasa'
  get 'balance_fecha', to: 'incomes#balance_fecha', as: 'balance_fecha'
  get 'balance_afecha/:cottage_id/:fecha_d/:fecha_h', to: 'incomes#balance_afecha', as: 'balance_afecha'
  get 'balance', to: 'incomes#balance', as: 'balance'

  get 'ingresopdf/:id_rent', to: 'rentals#ingresopdf', as:'ingresopdf'
 
  root 'welcome#index'


  # CK editor
  mount Ckeditor::Engine => '/ckeditor'
end

app/models/rental.rb
class Rental < ApplicationRecord
  include AASM

  belongs_to :person , required: false
  belongs_to :cottage, required: false
  has_many :incomes, dependent: :destroy
  has_many :companions, dependent: :destroy

  
  accepts_nested_attributes_for :companions, reject_if: proc { |attributes| attributes['nombre'].blank? }, allow_destroy: true
  accepts_nested_attributes_for :incomes, reject_if: proc { |attributes| attributes['importe'].blank? }, allow_destroy: true

  validate :fecha_libre
  validate :ganancia

  
  def fecha_libre
      @rentals = Rental.where.not(:id => id).where(cottage_id: cottage_id).where(fechadesde: fechadesde..fechahasta).where.not(estado: 'cancelada')
      @ok = 'S'
      if @rentals.any?
        @rentals.each do |r|
          if r.fecha_entrega > r.fechahasta
            @ok = 'N'
          end
        end
        if @ok == 'N'
          errors.messages[:fechadesde] << "La fecha ya se encuentra ocupada."
          errors.messages[:fechahasta] << "La fecha ya se encuentra ocupada."
        end  
      end
      if @ok == 'S'
        @rentals = Rental.where.not(:id => id).where(cottage_id: cottage_id).where(fechahasta: fechadesde..fechahasta).where.not(fecha_entrega: fechadesde..fechahasta).where.not(estado: 'cancelada')
        if @rentals.any?
          errors.messages[:fechadesde] << "La fecha ya se encuentra ocupada."
          errors.messages[:fechahasta] << "La fecha ya se encuentra ocupada."
        else  
          @rentals = Rental.where.not(:id => id).where(cottage_id: cottage_id).where(fecha_entrega: fechadesde).where("hora_entrega > ?", hora_entrada).where.not(estado: 'cancelada')   
          if @rentals.any?
            errors.messages[:hora_entrada] << "La casa todavía esta ocupada a esa hora."
          end
        end
      
      end
    
  end
  
  def ganancia
    if ganancia_dueno
      if ganancia_dueno > 0
        if ganancia_dueno > costo_total
          errors.messages[:ganancia_dueno] << "La ganancia no puede ser mayor al total."
        end
      else  
        return true
      end
    else
      return true
    end
  end
  
  def casa_cliente
    "#{self.cottage.nombre}, #{self.person.nombres} #{self.person.apellidos}, Total: $  #{self.importe_total}, Remanente: $  #{self.importe_restante} "
  end
  
  def importe_restante
    @suma =  Income.where(:rental_id => id).sum(:importe)
    @importe_total_ax = importe_total
    if @importe_total_ax
      @restante = @importe_total_ax - @suma 
    else
        @restante = 0
    end
    return @restante
  end
  
  def importe_total
    if total_luz
      @importe_total =  costo_total + total_luz
    else
      @importe_total =  costo_total
    end
    
    return @importe_total
  end
  
  
  aasm column: "estado" do
    state :ingresada, initial: true
    state :confirmada
    state :encurso
    state :finalizada
    state :cancelada
    
    event :confirmar do 
       transitions from: :ingresada, to: :confirmada
    end
    event :desconfirmar do 
       transitions from: :confirmada, to: :ingresada
    end
    event :cursar do 
       transitions from: :confirmada, to: :encurso
    end
    event :cancelar do 
       transitions from: :ingresada, to: :cancelada
       transitions from: :confirmada, to: :cancelada
       transitions from: :encurso, to: :cancelada
    end
    event :finalizar do 
      transitions from: :encurso, to: :finalizada
      transitions from: :confirmada, to: :finalizada
    end
    
  end
  
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: [:show, :edit, :update, :destroy, :informar]
  before_action :authenticate!
  # GET /rentals
  # GET /rentals.json

  def index
    @rentals = Rental.all
  end

  # GET /rentals/1
  # GET /rentals/1.json
  def show
    @rental.companions.build 
  end
  
  def informar
    @rental.informado = "S"
    @rental.save
  end

  
  
  def ingresopdf
    @rental = Rental.find(params[:id_rent])
    if @rental.confirmada? || @rental.ingresada?
      if @rental.may_cursar?
        @rental.cursar
        @rental.save
      end
    end
   render :layout => "empty"
  end
  
  
  def enviarCorreo
    ActionCorreoMailer.bienvenido_email('@gmail.com').deliver
  end
  
  def informado
    @rentals = Rental.all
    
    @rentals.each do |rental| 
      @companions = Companion.where(:rental_id => rental.id)
      @continuar = "S"
      if rental.informado != "S" 
        if rental.encurso? 
          if rental.person.documento != "" && rental.person.pais_origen_doc != '' && rental.person.document_type  && rental.person.sexo != "" && rental.person.nationality && rental.person.pais_residencia != "" && rental.fechadesde && rental.fechahasta && rental.person.fecha_nac 
            
            @companions.each do |companion| 
              if !companion.documento || !companion.nombre || !companion.apellido || !companion.pais_origen_doc || !companion.document_type || !companion.sexo || !companion.fecha_nac || !companion.pais_residencia || !companion.nationality 
                 @continuar = "N"
              end
            end
            
            if @continuar != "N"
              rental.informado = "S"
              rental.save(validate: false)
            end
          end
        end
      end
    end
  end

  
  def finalizar
      @rental = Rental.find(params[:id])
      if @rental.may_finalizar?
          @rental.finalizar
          if @rental.save(validate: false)
              render :json => @rental.to_json
          else  
              render :json => { :errors => @rental.errors.full_messages }
          end
      else
        render :json => { :errors => @rental.errors.full_messages }
      end
  end
  
  def cancelar
    
      @rental = Rental.find(params[:id])
      if !@rental.cancelada?
        if @rental.may_cancelar?
            @rental.cancelar
            if @rental.save(validate: false)
              render :json => @rental.to_json
            else  
              render :json => { :errors => @rental.errors.full_messages }
            end
        else
          render :json => { :errors => @rental.errors.full_messages }
        end
      else
        @rental.destroy
        render :json => @rental.to_json
      end
    
  end
  
  
  
  def controlarReserva
    
    @rentals = Rental.where(cottage_id: params[:cottage_id]).where(fechadesde: params[:fechadesde]..params[:fechahasta])
    @ok = 'S'
    if @rentals.any?
      @rentals.each do |r|
        if r.fecha_entrega > r.fechahasta
          @ok = 'N'
        end
      end
      if @ok == 'N'
        @error = 'Ya existe reserva para el periodo seleccionado.'
        render :json => { :errors => @error.to_json }
      end  
    end
    if @ok == 'S'
      @rentals = Rental.where(cottage_id: params[:cottage_id]).where(fechahasta:  params[:fechadesde]..params[:fechahasta]).where.not(fecha_entrega:  params[:fechadesde]..params[:fechahasta])
      if @rentals.any?
          @error = 'Ya existe reserva para el periodo seleccionado.'
         render :json => { :errors => @error.to_json }
      else  
        @rentals = Rental.where(cottage_id: params[:cottage_id]).where(fecha_entrega: params[:fechadesde]).where("hora_entrega > ?", params[:hora_entrada])   
        if @rentals.any?
          @error = 'La casa todavía esta ocupada a esa hora de entrada.'
          render :json => { :errors => @error.to_json }
        end
      end
    end
  end
  
    
  def modal_luz
    @rental = Rental.find(params[:idr])
    render :json => { :form => render_to_string(:partial => 'modalLuz', :locals => {:rental => @rental}) }   
  end
  
  # GET /rentals/new
  def new
    @rental = Rental.new
    @income = Income.new
    @rental.incomes.build 
    @rental.companions.build 
    @rental.estado = :ingresada
  end

  # GET /rentals/1/edit
  def edit
    @rental.incomes.build 
    @rental.companions.build 
    if @rental.incomes.present?
      if @rental.may_confirmar?
          @rental.confirmar
      end
    end
  end
  
  # POST /rentals
  # POST /rentals.json
  def create
    @rental = Rental.new(rental_params)

    respond_to do |format|
      if @rental.save
        if @rental.incomes.present?
          if @rental.may_confirmar?
              @rental.confirmar
              @rental.save
          end
        end
        format.html { redirect_to @rental, notice: 'Alquiler guardado correctamente.' }
        format.json { render :show, status: :created, location: @rental }
        
      else
        format.html { render :new }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rentals/1
  # PATCH/PUT /rentals/1.json
  def update
    respond_to do |format|
      if @rental.update(rental_params)
        if @rental.incomes.present?
          if @rental.may_confirmar?
              @rental.confirmar
              @rental.save
          end
        end
        format.html { redirect_to @rental, notice: 'Alquiler actualizado correctamente.' }
        format.json { render :show, status: :ok, location: @rental }
      else
        format.html { render :edit }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rentals/1
  # DELETE /rentals/1.json
  def destroy
    if @rental.cancelada?
      @rental.destroy
      respond_to do |format|
        if params[:commit] == 'Cancelar alquiler'
          format.html { redirect_to root_path, notice: 'Alquiler eliminado correctamente.' }
          format.json { head :no_content }
        else
          format.html { redirect_to rentals_url, notice: 'Alquiler eliminado correctamente.' }
          format.json { head :no_content }
        end
      end
    else
      respond_to do |format|
        if @rental.may_cancelar?
          @rental.cancelar   
          @rental.save
          if params[:commit] == 'Cancelar alquiler'
            format.html { redirect_to root_path, notice: 'Alquiler cancelado correctamente.' }
            format.json { head :no_content }
          else
            format.html { redirect_to rentals_url, notice: 'Alquiler cancelado correctamente.' }
            format.json { head :no_content }
          end
        else
           format.html { redirect_to root_path, notice: 'El Alquiler no puede ser cancelado.' }
           format.json { head :no_content }
        end
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental
      @rental = Rental.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rental_params
      params.require(:rental).permit(:fechadesde, :fechahasta, :valordia, :medidoringreso, :medidorfin, :valorkw, :cant_acomp, :descripcion, :person_id, :cottage_id,:fecha_entrega,:hora_entrega, :hora_entrada,:costo_total,:estado,:ganancia_dueno,:transporte, :informado, :total_luz, :pago_luz, incomes_attributes: [ :id, :fecha, :tipo, :importe  ], companions_attributes: [ :id, :nombre, :seg_nombre, :apellido, :seg_apellido, :documento, :pais_origen_doc, :document_type_id, :sexo, :nationality_id, :fecha_nac, :pais_residencia, :rental_id])
    end
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/rentals/edit.html.erb
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">
  
    <span class="ribbon-button-alignment">
      <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
        <i class="fa fa-refresh"></i>
      </span>
    </span>
  
    <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li><%= link_to 'Inicio', root_path %></li>
      <li><%= link_to 'Alquileres', rentals_path %></li>     
      <li>Editar Alquiler</li>
    </ol>
    <!-- end breadcrumb -->
  </div>
<!-- END RIBBON -->
<% end %>


<!-- MAIN CONTENT -->
<div id="content">
  <!-- widget grid -->
  <section id="widget-grid" class="">
    <!-- row -->
    <div class="row">

      <!-- NEW COL START -->
        <article class="col-sm-12 col-md-12 col-lg-6">
         

          <%= render 'form', rental: @rental %>


        </article>
      <!-- WIDGET END -->
    </div>
    <!-- end row -->   

  </section>
  <!-- end widget grid -->
</div>

app/views/rentals/index.html.erb
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">
  
    <span class="ribbon-button-alignment">
      <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Advertencia! se perderán los cambios no guardados. " data-html="true">
        <i class="fa fa-refresh"></i>
      </span>
    </span>
  
    <!-- breadcrumb -->
        <ol class="breadcrumb">
      <li><%= link_to 'Inicio', root_path %></li>
      <li><%= link_to 'Alquileres', rentals_path %></li>   
      
    </ol>

    <!-- end breadcrumb -->
  </div>
<!-- END RIBBON -->
<% end %>

<!-- MAIN CONTENT -->
<div id="content">

  <!-- widget grid -->
  <section id="widget-grid" class="">
    <!-- row -->
    <div class="row">

      <!-- NEW WIDGET START -->
      <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                
        <!-- Widget ID (each widget will need unique ID)-->
        <div class="jarviswidget jarviswidget-color-green" id="wid-id-3" data-widget-editbutton="false" data-widget-deletebutton="false" data-widget-colorbutton="false">
     
          <header>
            <span class="widget-icon"> <i class="fa fa-table"></i> </span>
            <h2>Alquileres</h2>  
          </header>
  
          <!-- widget div-->
          <div>
  
            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
              <!-- This area used as dropdown edit box -->  
            </div>
            <!-- end widget edit box -->
  
            <!-- widget content -->
            <div class="widget-body no-padding">
  
              <table id="datatable_tabletools" class="table table-striped table-bordered table-hover" width="100%">
                <thead>
                  <tr>
                    <th data-class="expand">Casa</th>
                    <th data-hide="expand">Cliente</th>
                    <th data-hide="phone">Fecha Entrada</th>
                    <th data-hide="phone">Fecha Salida</th>
                    <th data-hide="phone">Fecha Entrega</th>
                    <th data-hide="phone">Hora Entrada</th>
                    <th data-hide="phone">Hora Entrega</th>
                    <th data-hide="phone">Precio/Día</th>
                    <th data-hide="phone">Costo Total</th>
                    <th data-hide="phone">Paga Luz?</th>
                    <th data-hide="phone">Estado</th>
                    <th data-hide="expand">Acciones</th>                    
                  </tr>
                </thead>
                <tbody>
                  <% @rentals.each do |rental| %>
                    <tr>
                      <td><%= rental.cottage.nombre if rental.cottage %></td>
                      <td><%= rental.person.nombres if rental.person %>, <%=  rental.person.apellidos if rental.person %></td>
                      <td><%= rental.fechadesde.strftime("%d/%m/%Y") if rental.fechadesde %></td>
                      <td><%= rental.fechahasta.strftime("%d/%m/%Y") if rental.fechahasta %></td>
                      <td><%= rental.fecha_entrega.strftime("%d/%m/%Y") if rental.fecha_entrega %></td>
                      <% if rental.hora_entrada %>
                        <td><%= rental.hora_entrada.to_formatted_s(:time) %></td>
                      <% else %>
                        <td>00:00</td>
                      <% end %> 
                    
                      <% if rental.hora_entrega %>
                        <td><%= rental.hora_entrega.to_formatted_s(:time) %></td>
                      <% else %>
                        <td>00:00</td>
                      <% end %> 
                      <td><%= rental.valordia if rental.valordia %></td>
                      <td><%= rental.costo_total  if rental.costo_total %></td>
                      <% if rental.medidoringreso %>
                        <td>SI</td>
                      <% else %>
                        <td>NO</td>
                      <% end %>
                      <td><%= rental.estado if rental.estado %></td>
                      <td>
                        <%= link_to '', rental, class: 'btn btn-xs btn-default fa fa-eye' %>
                        <%= link_to '', edit_rental_path(rental), class: 'btn btn-xs btn-default fa fa-pencil' %>
                        <%= link_to '', rental, method: :delete, data: { confirm: 'Esta seguro que desea cancelar?' }, class: 'btn btn-xs btn-default fa fa-times'%>
                        <%= link_to '', ingresopdf_path(rental), target: :_blank , class: 'btn btn-xs btn-default fa fa-file' %>
                       
                      
                      </td>
                    </tr>
                  <% end %>
                </tbody>
              </table>  
            </div>
            <!-- end widget content -->  
          </div>
          <!-- end widget div -->  
        </div>
        <!-- end widget -->  
      </article>
      <!-- WIDGET END -->
    </div>
    <!-- end row -->   
  </section>
  <!-- end widget grid -->

<!-- END MAIN CONTENT -->


 <br>

<%= link_to 'Nuevo Alquiler', new_rental_path, class: 'btn btn-success' %>
</div>
<!-- END MAIN CONTENT -->

<% content_for :scripts do %>
  <script type="text/javascript">

    // DO NOT REMOVE : GLOBAL FUNCTIONS!

    $(document).ready(function() {

      pageSetUp();
    
      var responsiveHelper_datatable_tabletools = undefined;

      var breakpointDefinition = {
        tablet : 1024,
        phone : 480
      };
     
      
     $('#datatable_tabletools').DataTable( {
          dom: "<'dt-toolbar'<'col-xs-12 col-sm-6'f> <'col-sm-6 col-xs-6 hidden-xs'BT>r>"+
              "t"+ "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
          buttons: [
              {
                  extend: 'csvHtml5',
                  text: 'CSV',
                  title: 'Alquileres',
                  fieldSeparator: ";",
                  exportOptions: {
                      columns: [0,1,2,3,4,5,6,7,8,9,10]
                  }
              },
              {
                  extend: 'pdfHtml5',
                  text: 'PDF',
                  title: 'Alquileres',
                  exportOptions: {
                      columns: [0,1,2,3,4,5,6,7,8,9,10]
                  }
              },
              {
                  extend: 'excelHtml5',
                  title:'Alquileres',
                  text: 'EXCEL',
                  exportOptions: {
                      columns: [0,1,2,3,4,5,6,7,8,9,10]
                  }
              }                   
              
          ],
          language: {
              search: '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>',
              processing: "Procesando...",
              lengthMenu:    "Afficher _MENU_ &eacute;l&eacute;ments",
              info:           "Mostrando _END_ de _MAX_ registros",
              infoEmpty:      "No hay datos para mostrar",
              infoFiltered:   "(filtrado de _MAX_ registros totales)",
              infoPostFix:    "",
              loadingRecords: "Cargando registros...",
              zeroRecords:    "No hay datos para mostrar",
              emptyTable:     "No hay datos para mostrar",
              paginate: {
                  first:      "Primer",
                  previous:   "Anterior",
                  next:       "Siguiente",
                  last:       "Ultimo"
              },
             
          },
          "pageLength": 10,
          "autoWidth" : true,
          "preDrawCallback" : function() {
            // Initialize the responsive datatables helper once.
            if (!responsiveHelper_datatable_tabletools) {
              responsiveHelper_datatable_tabletools = new ResponsiveDatatablesHelper($('#datatable_tabletools'), breakpointDefinition);
            }
          },
          "rowCallback" : function(nRow) {
            responsiveHelper_datatable_tabletools.createExpandIcon(nRow);
          },
          "drawCallback" : function(oSettings) {
            responsiveHelper_datatable_tabletools.respond();
          }
          
          
      });
      
       //Cambio clases a los botones de CSV,PDF,XLS
      $(".dt-buttons").addClass("DTTT_container");
      $(".dt-button").addClass("DTTT_button");
      $(".dt-button").removeClass("dt-button buttons-csv buttons-html5");
      $(".dt-buttons").removeClass("dt-buttons");

    })

  </script>
<% end %>

app/views/rentals/new.html.erb
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">
  
    <span class="ribbon-button-alignment">
      <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Advertencia! se perderán los cambios no guardados. " data-html="true">
        <i class="fa fa-refresh"></i>
      </span>
    </span>
  
    <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li><%= link_to 'Inicio', root_path %></li>
      <li><%= link_to 'Alquileres', rentals_path %></li>     
      <li>Nuevo Alquiler</li>
    </ol>
    <!-- end breadcrumb -->
  </div>
<!-- END RIBBON -->
<% end %>

<!-- MAIN CONTENT -->
<div id="content">
  <!-- widget grid -->
  <section id="widget-grid" class="">
    <!-- row -->
    <div class="row">

      <!-- NEW COL START -->
        <article class="col-sm-12 col-md-12 col-lg-6">
         
          <%= render 'form', rental: @rental %>

        </article>
      <!-- WIDGET END -->
    </div>
    <!-- end row -->   
  </section>
  <!-- end widget grid -->

</div>

app/views/rentals/show.html.erb
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">
  
    <span class="ribbon-button-alignment">
      <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Advertencia! se perderán los cambios no guardados. " data-html="true">
        <i class="fa fa-refresh"></i>
      </span>
    </span>
  
    <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li><%= link_to 'Inicio', root_path %></li>
      <li><%= link_to 'Alquileres', rentals_path %></li>     
      <li>Ver Alquiler</li>
    </ol>
    <!-- end breadcrumb -->
  </div>
<!-- END RIBBON -->
<% end %>
<!-- MAIN CONTENT -->
<div id="content">
<!-- widget grid -->
  <section id="widget-grid" class="">
    <!-- row -->
    <div class="row">

      <!-- NEW COL START -->
        <article class="col-sm-12 col-md-12 col-lg-6">

			<div class="jarviswidget jarviswidget-color-green" id="wid-id-3" data-widget-editbutton="false" data-widget-deletebutton="false" data-widget-colorbutton="false" >
				<header>
					<span class="widget-icon"> <i class="fa fa-eye"></i> </span>
					<h2>Ver Alquiler </h2>  
				</header>
				
				<!-- widget div-->
				<div>
					<!-- widget edit box -->
				<div class="jarviswidget-editbox">
						<!-- This area used as dropdown edit box -->
				</div>
					<!-- end widget edit box -->
				
					<!-- widget content -->
					<!--<div class="widget-body no-padding">	-->	
						<fieldset>          	
							<!-- widget div-->
							<div>
								<!-- widget edit box -->
								<div class="jarviswidget-editbox">
									<!-- This area used as dropdown edit box -->
								</div>
								<!-- end widget edit box -->
					
								<!-- widget content -->
								<div class="widget-body no-padding">
									<form class="smart-form">
										<header>
											<label class="label">Casa</label>
											<label class="input">
												<%= @rental.cottage.nombre %>
											</label>
											
											<label class="label">Cliente</label>
											<label class="input">
												<%= @rental.person.nombres %>, <%= @rental.person.apellidos %>
											</label>
										</header>
										<fieldset>

											<section>
												<label class="label">Fecha Entrada</label>
												<label class="input">
													<%= @rental.fechadesde.strftime("%d/%m/%Y") %>
												</label>
											</section>
											<section>
												<label class="label">Hora Entrada</label>
												<label class="input">
													<% if @rental.hora_entrada %>
							                        	<%= @rental.hora_entrada.to_formatted_s(:time)   %>
							                      	<% else %>
							                        	00:00
							                      	<% end %>
												</label>
											</section>
											
											<section>
												<label class="label">Fecha Salida</label>
												<label class="input">
													<%= @rental.fechahasta.strftime("%d/%m/%Y") %>
												</label>
											</section>
											
											<section>
												<label class="label">Fecha Entrega</label>
												<label class="input">
													<%= @rental.fecha_entrega.strftime("%d/%m/%Y") %>
												</label>
											</section>
											
											<section>
												<label class="label">Hora Entrega</label>
												<label class="input">
													<% if @rental.hora_entrega %>
							                        	<%= @rental.hora_entrega.to_formatted_s(:time)   %>
							                      	<% else %>
							                        	00:00
							                      	<% end %>
												</label>
											</section>

											<section>
												<label class="label">Precio/Día</label>
												<label class="input">
													<%= @rental.valordia %>
												</label>
											</section>
											<section>
												
											<section>
												<label class="label">Costo Total</label>
												<label class="input">
													<%= @rental.costo_total %>
												</label>
											</section>
											
											<section>
												<label class="label">Ganancia Dueño</label>
												<label class="input">
													<%= @rental.ganancia_dueno %>
												</label>
											</section>
            
										  
										  <section>
												<label class="label">Medidor KW Ingreso</label>
												<label class="input">
													<%= @rental.medidoringreso %>
												</label>
											</section>
											
											<section>
												<label class="label">Medidor KW Fin</label>
												<label class="input">
													<%= @rental.medidorfin %>
												</label>
											</section>
                      
                      						<section>
												<label class="label">Precio/KW</label>
												<label class="input">
													<%= @rental.valorkw %>
												</label>
											</section>
                  
                      						<section>
												<label class="label">Cant. Acompañantes</label>
												<label class="input">
													<%= @rental.cant_acomp %>
												</label>
											</section>
                      
                     						<section>
												<label class="label">Descripción</label>
												<label class="input">
													<%= @rental.descripcion %>
												</label>
											</section>
											
											<section>
												<label class="label">Transporte</label>
												<label class="input">
													<%= @rental.transporte %>
												</label>
											</section>

                     
										</fieldset>
										<footer>
										 	<div>
							               		<%= link_to 'Volver', rentals_path, class: 'btn btn-default'  %>
							            	</div>
										</footer>
									</form>
								</div>
							</div>
						</fieldset>
				<!--	</div>-->
				</div>
			</div>	
        </article>
      <!-- WIDGET END -->
    </div>
    <!-- end row -->   
 </section>
  <!-- end widget grid -->
</div>