config/routes.rb
Rails.application.routes.draw do

  resources :companions
  resources :providers
  resources :expenses
  resources :incomes do 
    collection do 
      get :modal_new
    end
  end
  resources :rentals do
    collection do 
      post :finalizar
      post :cancelar
      post :informado
      post :enviarCorreo
      post :controlarReserva
      get :modal_luz
    end
  end
  
  resources :phones
  resources :emails
  resources :people
  resources :document_types
  resources :categories
  resources :nationalities
  resources :cottages
  resource :sessions, only: [:create, :new]
  resources :identities

  
  delete 'log_out' => 'sessions#destroy', as: :log_out
  get 'log_in' => 'sessions#new', as: :log_in
  get 'sign_up' => 'identities#new', as: :sign_up
  
  get 'welcome/index'
  get 'welcome/index_wiz'
  get 'welcome/calendarfull'
  
  get 'clientes' => 'people#index_cliente'
  get 'duenoscobro/:id_dueno', to: 'people#duenoscobro', as:'duenoscobro'
  get 'reporteduenos', to: 'people#reporteduenos', as:'reporteduenos'
  get 'clientes_rentas', to: 'people#clientes_rentas', as:'clientes_rentas'
  get 'clientes_rentas_faltantes', to: 'people#clientes_rentas_faltantes', as:'clientes_rentas_faltantes'
  get 'agendacuentas', to: 'people#agendacuentas', as:'agendacuentas'
  
  get 'reporte_ganancias', to: 'people#reporte_ganancias'
  get 'reporte_ganancias_detalle', to: 'people#reporte_ganancias_detalle', as: 'reporte_ganancias_detalle'

  get 'reporteCasa/:id_rep', to: 'cottages#reporte', as: 'rep'
  get 'calendariocasa', to: 'cottages#calendariocasa'
  get 'balance_fecha', to: 'incomes#balance_fecha', as: 'balance_fecha'
  get 'balance_afecha/:cottage_id/:fecha_d/:fecha_h', to: 'incomes#balance_afecha', as: 'balance_afecha'
  get 'balance', to: 'incomes#balance', as: 'balance'

  get 'ingresopdf/:id_rent', to: 'rentals#ingresopdf', as:'ingresopdf'
 
  root 'welcome#index'


  # CK editor
  mount Ckeditor::Engine => '/ckeditor'
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :expenses
    validates :descripcion, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate!
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to categories_path , notice: 'Categoría guardada correctamente.' }
      else
       format.html { render :new , alert: 'Categoría tiene errores.' }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to categories_path, notice: 'Categoría actualizada correctamente.' }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Categoría eliminada correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:descripcion)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
    <!-- Widget ID (each widget will need unique ID)-->
    <div class="jarviswidget jarviswidget-color-green" id="wid-id-3" data-widget-editbutton="false"  data-widget-deletebutton="false" data-widget-colorbutton="false">
   
    <header>
      <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
      <h2>Categoría</h2>  
    </header>
  
    <!-- widget div-->
    <div>
  
      <!-- widget edit box -->
      <div class="jarviswidget-editbox">
        <!-- This area used as dropdown edit box -->
  
      </div>
      <!-- end widget edit box -->
  
      <!-- widget content -->
      <div class="widget-body no-padding">
  
        <%= form_for(@category, html:{:class => 'smart-form'}) do |f| %>
          <fieldset>         
            
            <section>
              <label>Descripcíon</label>
              <label class="input"> <i class="icon-append fa fa-gears"></i>
                <%= f.text_field :descripcion, placeholder: 'Descripción'%>     
                
              </label>
            </section>
          </fieldset>
          <footer>
            <%= f.submit 'Confirmar', class:'btn btn-success'   %>  
            <div>
               <%= link_to 'Volver', categories_path, class: 'btn btn-default'  %>
            </div>
          </footer>
        <% end %>
  
      </div>
      <!-- end widget content -->
  
    </div>
    <!-- end widget div -->
  
  </div>
  <!-- end widget -->

app/views/categories/edit.html.erb
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">
  
    <span class="ribbon-button-alignment">
      <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
        <i class="fa fa-refresh"></i>
      </span>
    </span>
  
    <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li><%= link_to 'Inicio', root_path %></li>
      <li><%= link_to 'Categorías', categories_path %></li>     
      <li>Editar Categoría</li>
    </ol>
    <!-- end breadcrumb -->
  </div>
<!-- END RIBBON -->
<% end %>

<!-- MAIN CONTENT -->
<div id="content">
  <!-- widget grid -->
  <section id="widget-grid" class="">
    <!-- row -->
    <div class="row">

      <!-- NEW COL START -->
        <article class="col-sm-12 col-md-12 col-lg-6">
         

          <%= render 'form' %>


        </article>
      <!-- WIDGET END -->
    </div>
    <!-- end row -->   

  </section>
  <!-- end widget grid -->

</div>


					

app/views/categories/index.html.1.erb
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">
  
    <span class="ribbon-button-alignment">
      <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Advertencia! se perderán los cambios no guardados. " data-html="true">
        <i class="fa fa-refresh"></i>
      </span>
    </span>
  
    <!-- breadcrumb -->
        <ol class="breadcrumb">
      <li><%= link_to 'Inicio', root_path %></li>
      <li><%= link_to 'Categorías', categories_path %></li>   
      
    </ol>

    <!-- end breadcrumb -->
  </div>
<!-- END RIBBON -->
<% end %>

<!-- MAIN CONTENT -->
<div id="content">

  <!-- widget grid -->
  <section id="widget-grid" class="">
    <!-- row -->
    <div class="row">

      <!-- NEW WIDGET START -->
      <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                
        <!-- Widget ID (each widget will need unique ID)-->
        <div class="jarviswidget jarviswidget-color-green" id="wid-id-3" data-widget-editbutton="false" data-widget-deletebutton="false" data-widget-colorbutton="false">
     
          <header>
            <span class="widget-icon"> <i class="fa fa-table"></i> </span>
            <h2>Categorías</h2>  
          </header>
  
          <!-- widget div-->
          <div>
  
            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
              <!-- This area used as dropdown edit box -->  
            </div>
            <!-- end widget edit box -->
  
            <!-- widget content -->
            <div class="widget-body no-padding">
  
              <table id="datatable_tabletools" class="table table-striped table-bordered table-hover" width="100%">
                <thead>
                  <tr>
                    <th data-class="expand">Descripción</th>
                    <th data-hide="expand">Acciones</th>                    
                  </tr>
                </thead>
                <tbody>
                  <% @categories.each do |category| %>
                    
                    <tr>    
                      <td><%= category.descripcion %></td>                      
                       <td><%= link_to '', category, class: 'btn btn-xs btn-default fa fa-eye'%>
                          <%= link_to '', edit_category_path(category) , class: 'btn btn-xs btn-default fa fa-pencil' %>
                          <%= link_to '', category, method: :delete, data: { confirm: 'Esta seguro que desea eliminar?' }, class: 'btn btn-xs btn-default fa fa-times' %>
                      </td>
                    </tr>
                    
                  <% end %>                   
                </tbody>
              </table>  
            </div>
            <!-- end widget content -->  
          </div>
          <!-- end widget div -->  
        </div>
        <!-- end widget -->  
      </article>
      <!-- WIDGET END -->
    </div>
    <!-- end row -->   
  </section>
  <!-- end widget grid -->

<!-- END MAIN CONTENT -->



 <br>
 <%= link_to 'Nueva Categoría', new_category_path, class: 'btn btn-success' %>
</div>


<% content_for :scripts do %>
  <script type="text/javascript">

    // DO NOT REMOVE : GLOBAL FUNCTIONS!

    $(document).ready(function() {

      pageSetUp();
      
      var responsiveHelper_datatable_tabletools = undefined;

      var breakpointDefinition = {
        tablet : 1024,
        phone : 480
      };
      
       
      /* TABLETOOLS */
      $('#datatable_tabletools').dataTable({

        // Tabletools options:
        //   https://datatables.net/extensions/tabletools/button_options
        "sDom": "<'dt-toolbar'<'col-xs-12 col-sm-6'f><'col-sm-6 col-xs-6 hidden-xs'T>r>"+
        "t"+
        "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
        "oLanguage": {
          "sSearch": '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>'
        },
        buttons: [
            'copy', 'excel', 'pdf'
        ],
        "autoWidth" : true,
        "preDrawCallback" : function() {
          // Initialize the responsive datatables helper once.
          if (!responsiveHelper_datatable_tabletools) {
            responsiveHelper_datatable_tabletools = new ResponsiveDatatablesHelper($('#datatable_tabletools'), breakpointDefinition);
          }
        },
        "rowCallback" : function(nRow) {
          responsiveHelper_datatable_tabletools.createExpandIcon(nRow);
        },
        "drawCallback" : function(oSettings) {
          responsiveHelper_datatable_tabletools.respond();
        }
      });

      /* END TABLETOOLS */

    })

  </script>
<% end %>

app/views/categories/index.html.erb
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">
  
    <span class="ribbon-button-alignment">
      <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Advertencia! se perderán los cambios no guardados. " data-html="true">
        <i class="fa fa-refresh"></i>
      </span>
    </span>
  
    <!-- breadcrumb -->
        <ol class="breadcrumb">
      <li><%= link_to 'Inicio', root_path %></li>
      <li><%= link_to 'Categorías', categories_path %></li>   
      
    </ol>

    <!-- end breadcrumb -->
  </div>
<!-- END RIBBON -->
<% end %>

<!-- MAIN CONTENT -->
<div id="content">

  <!-- widget grid -->
  <section id="widget-grid" class="">
    <!-- row -->
    <div class="row">

      <!-- NEW WIDGET START -->
      <article class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                
        <!-- Widget ID (each widget will need unique ID)-->
        <div class="jarviswidget jarviswidget-color-green" id="wid-id-3" data-widget-editbutton="false" data-widget-deletebutton="false" data-widget-colorbutton="false">
     
          <header>
            <span class="widget-icon"> <i class="fa fa-table"></i> </span>
            <h2>Categorías</h2>  
          </header>
  
          <!-- widget div-->
          <div>
  
            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
              <!-- This area used as dropdown edit box -->  
            </div>
            <!-- end widget edit box -->
  
            <!-- widget content -->
            <div class="widget-body no-padding">
  
              <table id="datatable_tabletools" class="table table-striped table-bordered table-hover" width="100%">
                <thead>
                  <tr>
                    <th data-class="expand">Descripción</th>
                    <th data-hide="expand">Acciones</th>                    
                  </tr>
                </thead>
                <tbody>
                  <% @categories.each do |category| %>
                    
                    <tr>    
                      <td><%= category.descripcion %></td>                      
                       <td><%= link_to '', category, class: 'btn btn-xs btn-default fa fa-eye'%>
                          <%= link_to '', edit_category_path(category) , class: 'btn btn-xs btn-default fa fa-pencil' %>
                          <%= link_to '', category, method: :delete, data: { confirm: 'Esta seguro que desea eliminar?' }, class: 'btn btn-xs btn-default fa fa-times' %>
                      </td>
                    </tr>
                    
                  <% end %>                   
                </tbody>
              </table>  
            </div>
            <!-- end widget content -->  
          </div>
          <!-- end widget div -->  
        </div>
        <!-- end widget -->  
      </article>
      <!-- WIDGET END -->
    </div>
    <!-- end row -->   
  </section>
  <!-- end widget grid -->

<!-- END MAIN CONTENT -->



 <br>
 <%= link_to 'Nueva Categoría', new_category_path, class: 'btn btn-success' %>
</div>


<% content_for :scripts do %>
  <script type="text/javascript">

    // DO NOT REMOVE : GLOBAL FUNCTIONS!

    $(document).ready(function() {

      pageSetUp();
      
      var responsiveHelper_datatable_tabletools = undefined;

      var breakpointDefinition = {
        tablet : 1024,
        phone : 480
      };
      
       
     $('#datatable_tabletools').DataTable( {
          dom: "<'dt-toolbar'<'col-xs-12 col-sm-6'f> <'col-sm-6 col-xs-6 hidden-xs'BT>r>"+
              "t"+ "<'dt-toolbar-footer'<'col-sm-6 col-xs-12 hidden-xs'i><'col-sm-6 col-xs-12'p>>",
          buttons: [
              {
                  extend: 'csvHtml5',
                  text: 'CSV',
                  title: 'Categorias',
                  fieldSeparator: ";",
                  exportOptions: {
                      columns: [0]
                  }
              },
              {
                  extend: 'pdfHtml5',
                  text: 'PDF',
                  title: 'Categorias',
                  exportOptions: {
                      columns: [0]
                  }
              },
              {
                  extend: 'excelHtml5',
                  title:'Categorias',
                  text: 'EXCEL',
                  exportOptions: {
                      columns: [0]
                  }
              }                   
              
          ],
          language: {
              search: '<span class="input-group-addon"><i class="glyphicon glyphicon-search"></i></span>',
              processing: "Procesando...",
              lengthMenu:    "Afficher _MENU_ &eacute;l&eacute;ments",
              info:           "Mostrando _END_ de _MAX_ registros",
              infoEmpty:      "No hay datos para mostrar",
              infoFiltered:   "(filtrado de _MAX_ registros totales)",
              infoPostFix:    "",
              loadingRecords: "Cargando registros...",
              zeroRecords:    "No hay datos para mostrar",
              emptyTable:     "No hay datos para mostrar",
              paginate: {
                  first:      "Primer",
                  previous:   "Anterior",
                  next:       "Siguiente",
                  last:       "Ultimo"
              },
             
          },
          "pageLength": 10,
          "autoWidth" : true,
          "preDrawCallback" : function() {
            // Initialize the responsive datatables helper once.
            if (!responsiveHelper_datatable_tabletools) {
              responsiveHelper_datatable_tabletools = new ResponsiveDatatablesHelper($('#datatable_tabletools'), breakpointDefinition);
            }
          },
          "rowCallback" : function(nRow) {
            responsiveHelper_datatable_tabletools.createExpandIcon(nRow);
          },
          "drawCallback" : function(oSettings) {
            responsiveHelper_datatable_tabletools.respond();
          }
          
          
      });
      
       //Cambio clases a los botones de CSV,PDF,XLS
      $(".dt-buttons").addClass("DTTT_container");
      $(".dt-button").addClass("DTTT_button");
      $(".dt-button").removeClass("dt-button buttons-csv buttons-html5");
      $(".dt-buttons").removeClass("dt-buttons");
    

    })

    
  </script>
<% end %>

app/views/categories/new.html.erb
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">
  
    <span class="ribbon-button-alignment">
      <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Advertencia! se perderán los cambios no guardados. " data-html="true">
        <i class="fa fa-refresh"></i>
      </span>
    </span>
  
    <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li><%= link_to 'Inicio', root_path %></li>
      <li><%= link_to 'Categorías', categories_path %></li>     
      <li>Nueva</li>
    </ol>
    <!-- end breadcrumb -->
  </div>
<!-- END RIBBON -->
<% end %>

<!-- MAIN CONTENT -->
<div id="content">

  <!-- widget grid -->
  <section id="widget-grid" class="">
    <!-- row -->
    <div class="row">

      <!-- NEW COL START -->
        <article class="col-sm-12 col-md-12 col-lg-6">
         
          <%= render 'form' %>

        </article>
      <!-- WIDGET END -->
    </div>
    <!-- end row -->   
  </section>
  <!-- end widget grid -->
</div>

app/views/categories/show.html.erb
<% content_for :ribbon do %>
  <!-- RIBBON -->
  <div id="ribbon">
  
    <span class="ribbon-button-alignment">
      <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Advertencia! se perderán los cambios no guardados. " data-html="true">
        <i class="fa fa-refresh"></i>
      </span>
    </span>
  
    <!-- breadcrumb -->
    <ol class="breadcrumb">
      <li><%= link_to 'Inicio', root_path %></li>
      <li><%= link_to 'Categorías', categories_path %></li>     
      <li>Ver Categoría</li>
    </ol>
    <!-- end breadcrumb -->
  </div>
<!-- END RIBBON -->
<% end %>

<!-- MAIN CONTENT -->
<div id="content">
	
	<!-- widget grid -->
  <section id="widget-grid" class="">
    <!-- row -->
    <div class="row">

      <!-- NEW COL START -->
        <article class="col-sm-12 col-md-12 col-lg-6">

			<div class="jarviswidget jarviswidget-color-green" id="wid-id-3" data-widget-editbutton="false" >
				<header>
					<span class="widget-icon"> <i class="fa fa-eye"></i> </span>
					<h2>Ver Categoría</h2>  
				</header>
				
				<!-- widget div-->
				<div>
					<!-- widget edit box -->
				<div class="jarviswidget-editbox">
						<!-- This area used as dropdown edit box -->
				</div>
					<!-- end widget edit box -->
				
					<!-- widget content -->
					<!--<div class="widget-body no-padding">	-->	
						<fieldset>          	
							<!-- widget div-->
							<div>
								<!-- widget edit box -->
								<div class="jarviswidget-editbox">
									<!-- This area used as dropdown edit box -->
								</div>
								<!-- end widget edit box -->
					
								<!-- widget content -->
								<div class="widget-body no-padding">
									<form class="smart-form">
										<header>
											<label class="label">Descripción</label>
											<label class="input">
												<%= @category.descripcion %>
											</label>
										</header>
										<footer>
										 <%= link_to 'Volver', categories_path, class: 'btn btn-default'  %>
										</footer>
									</form>
								</div>
							</div>
						</fieldset>
				<!--	</div>-->
				</div>
			</div>	
        </article>
      <!-- WIDGET END -->
    </div>
    <!-- end row -->   
 </section>
  <!-- end widget grid -->
</div>